# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "CSharpier";
    version = "0.29.2";
    hash = "sha256-+Mrb7VGeKuMS4hEmejthFWuX5Ga299pbPScmFtSg644=";
  })
  (fetchNuGet {
    pname = "Macross.Json.Extensions";
    version = "3.0.0";
    hash = "sha256-nBoB4vY+R19jGPdnlN6hNmZjOeAEkOA1CS+DHLjZUJA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.TimeProvider";
    version = "8.0.1";
    hash = "sha256-TQRaWjk1aZu+jn/rR8oOv8BJEG31i6mPkf3BkIR7C+c=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "8.0.0";
    hash = "sha256-FU8qj3DR8bDdc1c+WeGZx/PCZeqqndweZM9epcpXjSo=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Abstractions";
    version = "8.2.0";
    hash = "sha256-e+BmN/Et9mTqWt4M38udL47M4wHHs25Ob299gJSBZIM=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.JsonWebTokens";
    version = "8.2.0";
    hash = "sha256-tOzI2GmMISuWO/vDtJIeKmYAaFPYjrB5NhpzCWWcIw4=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Logging";
    version = "8.2.0";
    hash = "sha256-JdrIo2Dg9UPu/eK5TIPKLWfRmvPGhKZrBCQL+MIv72I=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Tokens";
    version = "8.2.0";
    hash = "sha256-QxhnZVUrKKUZEKZgok2+4HjawuXZtVhXCJ2+BDomja8=";
  })
  (fetchNuGet {
    pname = "Octokit.Webhooks";
    version = "2.4.1";
    hash = "sha256-FZ2Eg432VkDh8fQWXkacGJNf9Uvv5LUCAU/xrqugnFc=";
  })
  (fetchNuGet {
    pname = "Octokit.Webhooks.AspNetCore";
    version = "2.4.1";
    hash = "sha256-UGRKHb8wwtNl1nMIp2hZs0DTQZmWOAFZB8MXzbRBV7g=";
  })
  (fetchNuGet {
    pname = "System.IdentityModel.Tokens.Jwt";
    version = "8.2.0";
    hash = "sha256-Htz1I19N0/IWHF8tbyZC90wCqI5xLh42jMXI3GXkCP4=";
  })
]
