// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Amaurot.Client.GitHub.Models
{
    /// <summary>
    /// Context around who pinned an issue comment and when it was pinned.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class NullablePinnedIssueComment : IParsable
    {
        /// <summary>The pinned_at property</summary>
        public DateTimeOffset? PinnedAt { get; set; }
        /// <summary>A GitHub user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Amaurot.Client.GitHub.Models.NullableSimpleUser? PinnedBy { get; set; }
#nullable restore
#else
        public global::Amaurot.Client.GitHub.Models.NullableSimpleUser PinnedBy { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Amaurot.Client.GitHub.Models.NullablePinnedIssueComment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Amaurot.Client.GitHub.Models.NullablePinnedIssueComment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Amaurot.Client.GitHub.Models.NullablePinnedIssueComment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pinned_at", n => { PinnedAt = n.GetDateTimeOffsetValue(); } },
                { "pinned_by", n => { PinnedBy = n.GetObjectValue<global::Amaurot.Client.GitHub.Models.NullableSimpleUser>(global::Amaurot.Client.GitHub.Models.NullableSimpleUser.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("pinned_at", PinnedAt);
            writer.WriteObjectValue<global::Amaurot.Client.GitHub.Models.NullableSimpleUser>("pinned_by", PinnedBy);
        }
    }
}
#pragma warning restore CS0618
