version: 2
updates:
  - directory: "/Amaurot.Processor"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"

  - directory: "/Amaurot.Receiver"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
