# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "Google.Api.CommonProtos";
    version = "2.16.0";
    hash = "sha256-fLv3T0U5GOW6tfsGxv/0N6MXQFfAnvPkyNipanh1a1k=";
  })
  (fetchNuGet {
    pname = "Google.Api.Gax";
    version = "4.9.0";
    hash = "sha256-3fmCAf2Ij1UQHiydlZM0J8QsfTNWrR5zs7ucCzsYM0s=";
  })
  (fetchNuGet {
    pname = "Google.Api.Gax.Grpc";
    version = "4.8.0";
    hash = "sha256-VSkP/9z3TB/o6NWUSFw3FfnQyHQP0vUILK5H11VOXuU=";
  })
  (fetchNuGet {
    pname = "Google.Api.Gax.Grpc";
    version = "4.9.0";
    hash = "sha256-hB3lu3AILs+RXMh3LRL5J+A+2tSw79WfYvkU5634GSY=";
  })
  (fetchNuGet {
    pname = "Google.Apis";
    version = "1.68.0";
    hash = "sha256-KUFT+rWxzeWVMWc34cqrFs1N/FxvG15vWqZruwWXHX4=";
  })
  (fetchNuGet {
    pname = "Google.Apis.Auth";
    version = "1.68.0";
    hash = "sha256-pptb3sxuFZMREdgGDJzdOSfn84XF5PMzzXwe+w7N+kQ=";
  })
  (fetchNuGet {
    pname = "Google.Apis.Core";
    version = "1.68.0";
    hash = "sha256-eoGiEopf3PfqAJYxBqomtV6f2mMBeXyjyXlXOAqbsis=";
  })
  (fetchNuGet {
    pname = "Google.Cloud.Compute.V1";
    version = "3.0.0";
    hash = "sha256-nvjc5jDV/demKBVbMy0ViK4pYXwNCIU/2NX7/jGZI4Q=";
  })
  (fetchNuGet {
    pname = "Google.LongRunning";
    version = "3.3.0";
    hash = "sha256-xjVvgwAqwiYIDDhbw2ex+EtM/kbx2cRM5yGwB5i7j+o=";
  })
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.28.2";
    hash = "sha256-GUaoreN2G4CSHnhaQJBS5jFfDKVmMyGE7b+9DV6lXPs=";
  })
  (fetchNuGet {
    pname = "Grpc.Auth";
    version = "2.66.0";
    hash = "sha256-Cpn5CRlNezA+xUvQQvZ1VrYlNkAYrEyrJS+/D5oWz2I=";
  })
  (fetchNuGet {
    pname = "Grpc.Core.Api";
    version = "2.66.0";
    hash = "sha256-XVZmvlUK0t4bWaIBUAoAm007VhUdUvSSlCDh6P4IV9c=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.Client";
    version = "2.66.0";
    hash = "sha256-bxK/5xFYWpqFmD8N79B79ymSt/u4aKRJkrO5I1ZxDgI=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.Common";
    version = "2.66.0";
    hash = "sha256-M/GsAvCs1vQ29xLYtK1tuxOhk5MPm5lmwn+DPhfcgkA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "6.0.0";
    hash = "sha256-49+H/iFwp+AfCICvWcqo9us4CzxApPKC37Q5Eqrw+JU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "6.0.0";
    hash = "sha256-SZke0jNKIqJvvukdta+MgIlGsrP2EdPkkS8lfLg7Ju4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "6.0.0";
    hash = "sha256-QNqcQ3x+MOK7lXbWkCzSOWa/2QyYNbdM/OEEbWN15Sw=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc=";
  })
  (fetchNuGet {
    pname = "System.CodeDom";
    version = "7.0.0";
    hash = "sha256-7IPt39cY+0j0ZcRr/J45xPtEjnSXdUJ/5ai3ebaYQiE=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "6.0.1";
    hash = "sha256-Xi8wrUjVlioz//TPQjFHqcV/QGhTqnTfUcltsNlcCJ4=";
  })
  (fetchNuGet {
    pname = "System.Management";
    version = "7.0.2";
    hash = "sha256-bJ21ILQfbHb8mX2wnVh7WP/Ip7gdVPIw+BamQuifTVY=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
  })
]
