// <auto-generated/>
#pragma warning disable CS0618
using Amaurot.Client.GitHub.Repos.Item.Item.Issues.Item.Comments;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Amaurot.Client.GitHub.Repos.Item.Item.Issues.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner}\{repo}\issues\{issue_number}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class WithIssue_numberItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The comments property</summary>
        public global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Item.Comments.CommentsRequestBuilder Comments
        {
            get => new global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Item.Comments.CommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithIssue_numberItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/issues/{issue_number}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithIssue_numberItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/issues/{issue_number}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
