// <auto-generated/>
#pragma warning disable CS0618
using Amaurot.Client.GitHub.Repos.Item.Item.Issues.Comments;
using Amaurot.Client.GitHub.Repos.Item.Item.Issues.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Amaurot.Client.GitHub.Repos.Item.Item.Issues
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner}\{repo}\issues
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class IssuesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The comments property</summary>
        public global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Comments.CommentsRequestBuilder Comments
        {
            get => new global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Comments.CommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Amaurot.Client.GitHub.repos.item.item.issues.item collection</summary>
        /// <param name="position">The number that identifies the issue.</param>
        /// <returns>A <see cref="global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberItemRequestBuilder"/></returns>
        public global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("issue_number", position);
                return new global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Item.WithIssue_numberItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.IssuesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IssuesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/issues", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.IssuesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IssuesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/issues", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
