// <auto-generated/>
#pragma warning disable CS0618
using Amaurot.Client.GitHub.Repos.Item.Item.Issues.Comments.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Amaurot.Client.GitHub.Repos.Item.Item.Issues.Comments
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner}\{repo}\issues\comments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class CommentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Amaurot.Client.GitHub.repos.item.item.issues.comments.item collection</summary>
        /// <param name="position">The unique identifier of the comment.</param>
        /// <returns>A <see cref="global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Comments.Item.WithComment_ItemRequestBuilder"/></returns>
        public global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Comments.Item.WithComment_ItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("comment_id", position);
                return new global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Comments.Item.WithComment_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Comments.CommentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/issues/comments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Amaurot.Client.GitHub.Repos.Item.Item.Issues.Comments.CommentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/issues/comments", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
