name: Amaurot
on:
  push:
    branches:
     - main
    paths:
      - Amaurot.Common/**
      - Amaurot.Processor/**
      - Amaurot.Receiver/**
      - npins/*

  pull_request:
    branches:
     - main
    paths:
      - Amaurot.Common/**
      - Amaurot.Processor/**
      - Amaurot.Receiver/**
      - npins/*

  workflow_dispatch:

jobs:
  Docker:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
          echo "trusted-users = root runner" | sudo tee -a /etc/nix/nix.conf

      - uses: cachix/cachix-action@v15
        with:
          name: drakon64-amaurot
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build -A processor-image -A receiver-image

      - run: |
          docker load < result
          docker load < result-2

      - run: |
          docker tag amaurot-processor:latest ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/amaurot-processor:latest
          docker tag amaurot-receiver:latest ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/amaurot-receiver:latest

      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker ${{ vars.GOOGLE_REGION }}-docker.pkg.dev

      - run: |
          docker push ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/amaurot-processor:latest
          docker push ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/amaurot-receiver:latest

      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: amaurot-processor
          image: ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/amaurot-processor:latest
          region: ${{ vars.GOOGLE_REGION }}

      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: amaurot-receiver
          image: ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/amaurot-receiver:latest
          region: ${{ vars.GOOGLE_REGION }}
