name: Amaurot
on:
  push:
    branches:
     - main
    paths:
      - Amaurot.Processor/**
      - Amaurot.Receiver/**

  pull_request:
    branches:
     - main
    paths:
      - Amaurot.Processor/**
      - Amaurot.Receiver/**

  workflow_dispatch:

jobs:
  Docker:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v15
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          diagnostic-endpoint: ""

      - uses: cachix/cachix-action@v15
        with:
          name: drakon64-amaurot
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build Amaurot.Processor/docker.nix Amaurot.Receiver/docker.nix

      - run: |
          docker load < result
          docker load < result-2

      - run: |
          docker tag amaurot-processor:latest ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/amaurot-processor:latest
          docker tag amaurot-receiver:latest ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/amaurot-receiver:latest

      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - run: |
          docker push ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/amaurot-processor:latest
          docker push ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}/amaurot-receiver:latest
